WITH joined_det AS (
    SELECT
        c.ID_PLANO,
        d.QT_ITEM_EVENTO_INFORMADO,
        d.VL_ITEM_EVENTO_INFORMADO,
        d.VL_ITEM_PAGO_FORNECEDOR,
        d.IND_PACOTE
    FROM HOSP_CONS c
    JOIN HOSP_DET d ON c.ID_EVENTO_ATENCAO_SAUDE = d.ID_EVENTO_ATENCAO_SAUDE
), grouped_det AS (
    SELECT
        j.ID_PLANO,
        MIN(j.QT_ITEM_EVENTO_INFORMADO) AS MIN_QT_ITEM_EVENTO_INFORMADO,
        MAX(j.QT_ITEM_EVENTO_INFORMADO) AS MAX_QT_ITEM_EVENTO_INFORMADO,
        MEDIAN(j.QT_ITEM_EVENTO_INFORMADO) AS MEDIAN_QT_ITEM_EVENTO_INFORMADO,
        MIN(j.VL_ITEM_EVENTO_INFORMADO) AS MIN_VL_ITEM_EVENTO_INFORMADO,
        MAX(j.VL_ITEM_EVENTO_INFORMADO) AS MAX_VL_ITEM_EVENTO_INFORMADO,
        MEDIAN(j.VL_ITEM_EVENTO_INFORMADO) AS MEDIAN_VL_ITEM_EVENTO_INFORMADO,
        MIN(j.VL_ITEM_PAGO_FORNECEDOR) AS MIN_VL_ITEM_PAGO_FORNECEDOR,
        MAX(j.VL_ITEM_PAGO_FORNECEDOR) AS MAX_VL_ITEM_PAGO_FORNECEDOR,
        MEDIAN(j.VL_ITEM_PAGO_FORNECEDOR) AS MEDIAN_VL_ITEM_PAGO_FORNECEDOR,
        STATS_MODE(j.IND_PACOTE) AS PRINCIPAL_IND_PACOTE,
        COUNT(DISTINCT j.IND_PACOTE) - 1 AS USA_OUTRO_IND_PACOTE
    FROM joined_det j
    GROUP BY j.ID_PLANO
), grouped_cons AS (
    SELECT
        ID_PLANO,
        COUNT(DISTINCT ID_EVENTO_ATENCAO_SAUDE) AS QTD_EVENTOS,
        MAX(FAIXA_ETARIA) AS FAIXA_ETARIA,
        STATS_MODE(SEXO) AS SEXO,
        STATS_MODE(CD_MUNICIPIO_BENEFICIARIO) AS CD_PRINCIPAL_MUNICIPIO_BENEFICIARIO,
        STATS_MODE(UF_PRESTADOR) AS UF_PRINCIPAL_PRESTADOR,
        MIN(ANO_MES_EVENTO) AS ANO_MES_PRIMEIRO_EVENTO,
        MAX(ANO_MES_EVENTO) AS ANO_MES_ULTIMO_EVENTO,
        MEDIAN(TEMPO_DE_PERMANENCIA) AS MEDIAN_TEMPO_DE_PERMANENCIA,
        MAX(TEMPO_DE_PERMANENCIA) AS MAX_TEMPO_DE_PERMANENCIA,
        MIN(TEMPO_DE_PERMANENCIA) AS MIN_TEMPO_DE_PERMANENCIA,
        MEDIAN(QT_DIARIA_ACOMPANHANTE) AS MEDIAN_QT_DIARIA_ACOMPANHANTE,
        MAX(QT_DIARIA_ACOMPANHANTE) AS MAX_QT_DIARIA_ACOMPANHANTE,
        MIN(QT_DIARIA_ACOMPANHANTE) AS MIN_QT_DIARIA_ACOMPANHANTE,
        MEDIAN(QT_DIARIA_UTI) AS MEDIAN_QT_DIARIA_UTI,
        MAX(QT_DIARIA_UTI) AS MAX_QT_DIARIA_UTI,
        MIN(QT_DIARIA_UTI) AS MIN_QT_DIARIA_UTI,
        STATS_MODE(LG_VALOR_PREESTABELECIDO) AS LG_VALOR_PREESTABELECIDO
    FROM hosp_cons
    GROUP BY ID_PLANO
), joined_tables AS (
    SELECT
        a.MIN_QT_ITEM_EVENTO_INFORMADO,
        a.MAX_QT_ITEM_EVENTO_INFORMADO,
        a.MEDIAN_QT_ITEM_EVENTO_INFORMADO,
        a.MIN_VL_ITEM_EVENTO_INFORMADO,
        a.MAX_VL_ITEM_EVENTO_INFORMADO,
        a.MEDIAN_VL_ITEM_EVENTO_INFORMADO,
        a.MIN_VL_ITEM_PAGO_FORNECEDOR,
        a.MAX_VL_ITEM_PAGO_FORNECEDOR,
        a.MEDIAN_VL_ITEM_PAGO_FORNECEDOR,
        a.PRINCIPAL_IND_PACOTE,
        a.USA_OUTRO_IND_PACOTE,
        b.*
    FROM grouped_det a
    JOIN grouped_cons b ON a.ID_PLANO = b.ID_PLANO
)
