WITH joined_tables AS (
    SELECT
        d.*
        c.ID_PLANO,
        c.FAIXA_ETARIA,
        c.SEXO,
        c.CD_MUNICIPIO_BENEFICIARIO,
        c.PORTE,
        c.CD_MODALIDADE,
        c.NM_MODALIDADE,
        c.CD_MUNICIPIO_PRESTADOR,
        c.CD_CARATER_ATENDIMENTO,
        c.CD_TIPO_INTERNACAO,
        c.CD_REGIME_INTERNACAO,
        c.CD_MOTIVO_SAIDA,
        c.CID_1,
        c.CID_2,
        c.CID_3,
        c.CID_4,
        c.QT_DIARIA_ACOMPANHANTE,
        c.QT_DIARIA_UTI,
        c.IND_ACIDENTE_DOENCA,
        c.LG_VALOR_PREESTABELECIDO,
        
    FROM HOSP_CONS c
    JOIN HOSP_DET d ON c.ID_EVENTO_ATENCAO_SAUDE = d.ID_EVENTO_ATENCAO_SAUDE
),

WITH grouped_cons as (
    SELECT
        ID_PLANO,
        COUNT(DISTINCT ID_EVENTO_ATENCAO_SAUDE) AS QTD_EVENTOS,
        MAX(FAIXA_ETARIA) AS FAIXA_ETARIA,
        STATS_MODE(SEXO) AS SEXO,
        STATS_MODE(CD_MUNICIPIO_BENEFICIARIO) AS CD_PRINCIPAL_MUNICIPIO_BENEFICIARIO,
        STATS_MODE(UF_PRESTADOR) AS UF_PRINCIPAL_PRESTADOR,
        MIN(ANO_MES_EVENTO) AS ANO_MES_PRIMEIRO_EVENTO,
        MAX(ANO_MES_EVENTO) AS ANO_MES_ULTIMO_EVENTO,
        MEDIAN(TEMPO_DE_PERMANENCIA) AS MEDIAN_TEMPO_DE_PERMANENCIA,
        MAX(TEMPO_DE_PERMANENCIA) AS MAX_TEMPO_DE_PERMANENCIA
    FROM hosp_cons
    GROUP BY ID_PLANO
)
